In [1]:
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [2]:
df = pd.read_table("isl_sentences_clean.txt", header=None, names=["sentence"])

In [3]:
df.head()

                             sentence
0              Where is the bathroom?
1         I need to use the bathroom.
2           Can I go to the bathroom?
3        The bathroom is on the left.
4  Please wait, I am in the bathroom.

# 1. Lowercasing

In [4]:
df['sentence'][0].lower()

'where is the bathroom?'

In [5]:
df['sentence'] = df['sentence'].str.lower()

In [6]:
df.head()

                             sentence
0              where is the bathroom?
1         i need to use the bathroom.
2           can i go to the bathroom?
3        the bathroom is on the left.
4  please wait, i am in the bathroom.

# 2. Removing HTML tags

## Regular expressions, Regex

In [7]:
import re

# Match the word "python" in the text
text = "I love python programming!"
match = re.search(r'python', text)
print(match.group())

python

In [8]:
# The re.search(r'python', text) function searches for the word "python" in the given text.
# The regular expression r'python' is looking for the exact match of the string "python".
# If a match is found, re.search() returns a match object.
# match.group() retrieves the matched string, in this case, "python"

- Identifying specific words or phrases in text, like extracting keywords or entities.

### Metacharacters

Metacharacters are special characters that define the behavior of the regex engine.

Common Metacharacters:

. - Matches any character except newline.

^ - Matches the start of a string.

$ - Matches the end of a string.

[] - Matches a character set.

| - Acts as an OR between patterns.

In [9]:
def match_pattern(pattern, text):
    match = re.search(pattern, text)
    if match:
        return match.group()
    else:
        return "No match found"

In [10]:
print(match_pattern(r'hello.w', "helloworld"))
print(match_pattern(r'hello.w', "hello world!"))

No match found
hello w

In [11]:
text = "The price is 100"
# Caret (^): Matches the start of the string.
print(match_pattern(r"^The", text))
print(match_pattern(r"^100", text))
# Dollar ($): Matches the end of the string.
print(match_pattern(r"The$", text))
print(match_pattern(r"100$", text))
# Asterisk (*): Matches 0 or more repetitions of the preceding pattern.
print(match_pattern(r"pri*", text))
print(match_pattern(r"llo*", "helloooo world"))
# Plus (+): Matches 1 or more repetitions of the preceding pattern.
print(match_pattern(r"pri+", text))
print(match_pattern(r"lo+", "helloooo world"))
print(match_pattern(r"llo+", "helloooo world"))
print(match_pattern(r"ll+", "helloooo world"))

The
No match found
No match found
100
pri
lloooo
pri
loooo
lloooo
ll

- Matching patterns at the start or end of sentences for sentence boundary detection

###  Character Classes
Character classes allow you to match one of a set of characters.

[abc] - Matches 'a', 'b', or 'c'.

[^abc] - Matches any character except 'a', 'b', or 'c'.

In [12]:
print((re.findall(r'[aeiou]', "hello worldu")))
print(re.findall(r'[^aeiou]', "hello worldu"))

['e', 'o', 'o', 'u']
['h', 'l', 'l', ' ', 'w', 'r', 'l', 'd']

- Extracting parts of text like named entities (e.g., extracting names from sentences)

### Quantifiers
Quantifiers specify how many times a pattern should appear.

-> * - Matches 0 or more of the preceding pattern.

-> + Matches 1 or more of the preceding pattern.

? - Matches 0 or 1 of the preceding pattern.

{n} - Matches exactly n occurrences of the preceding pattern.

{n,} - Matches n or more occurrences of the preceding pattern.

{n,m} - Matches between n and m occurrences of the preceding pattern.

In [13]:
match = re.findall(r'\d{1,4}', "1234 and 56")
print(match)

['1234', '56']

In [14]:
match = re.findall(r'\d{1,4}', "12345 and 56 55555")
print(match)

['1234', '5', '56', '5555', '5']

In [15]:
text = "12345 and 56 55555"
print(re.findall(r'\d*', text))

['12345', '', '', '', '', '', '56', '', '55555', '']

In [16]:
print(re.findall(r'\d+', text))

['12345', '56', '55555']

### substitution and replacement

In [17]:
print(re.sub(r'\d+', 'digit', text))

digit and digit digit

### removing html tags

In [18]:
text = """
<html>
<head>
<title>My Website</title>
</head>

<body>

<h1>Welcome to AI World</h1>

<p>This is a <b>machine learning</b> tutorial.</p>

<a href="https://example.com">Click Here</a>

<div>
    <p>Deep Learning and NLP are trending fields.</p>
</div>

</body>
</html>
"""

In [19]:
pattern = r'<.*?>'
clean_text = re.sub(pattern, '', text)
clean_text = re.sub(r'\s+', ' ', clean_text)
print(clean_text.strip())

My Website Welcome to AI World This is a machine learning tutorial. Click Here Deep Learning and NLP are trending fields.

# 3. Removing URLs

In [20]:
text = """
Hello everyone!

Visit our website at https://www.example.com for more information.

You can also check:
http://openai.com/blog

Follow us on:
https://twitter.com/openai

Machine learning tutorials:
https://www.kaggle.com/learn

Contact us anytime.

Thank you!
"""

In [21]:
pattern = r'https?://\S+|www\.\S+'
urls = re.findall(pattern, text)

In [22]:
print(urls)

['https://www.example.com', 'http://openai.com/blog', 'https://twitter.com/openai', 'https://www.kaggle.com/learn']

In [23]:
clean_text = re.sub(pattern, '', text)

In [24]:
print(clean_text.strip())

Hello everyone!

Visit our website at  for more information.

You can also check:


Follow us on:


Machine learning tutorials:


Contact us anytime.

Thank you!

# 4. Remove punctuations

In [25]:
import string
exclude = string.punctuation

In [26]:
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [27]:
def remove_punctuation(text):
    for char in exclude:
        text = text.replace(char, "")
    return text

In [28]:
import time
start = time.time()
print(remove_punctuation("Hello, world! This is a test."))
end = time.time()
print(f"Time taken: {end - start}")
time1 = end - start

Hello world This is a test
Time taken: 0.0

In [29]:
# above method is slow for large texts. We can use standard library to remove punctuation
def remove_punctuation_fast(text):
    return text.translate(str.maketrans('', '', exclude))

In [30]:
start = time.time()
print(remove_punctuation_fast("Hello, world! This is a test."))
end = time.time()
print(f"Time taken: {end - start}")
time2 = end - start

Hello world This is a test
Time taken: 0.0

In [31]:
import time
start = time.time()
df['sentence_punctuation'] = df['sentence'].apply(remove_punctuation)
end = time.time()
print(f"Time taken: {end - start}")
time1 = end - start

Time taken: 0.010579586029052734

In [32]:
import time
start = time.time()
df['sentence_punctuation_fast'] = df['sentence'].apply(remove_punctuation_fast)
end = time.time()
print(f"Time taken: {end - start}")
time2 = end - start

Time taken: 0.007570743560791016

In [33]:
time1/time2
# time1 is much higher than time2, which shows that the second method is much faster than the first method for removing punctuation from text.

1.3974302450085028

# 5. Chat word treatment

- when u chat on social media :-

- u : you
- FYI : for your information
- GN : good night
- GM : good morning

In [34]:
map = {
    "U":"You",
    "FYI":"For Your Information",
    "GM":"Good Morning",
    "ASAP":"As Soon As Possible"
}

In [35]:
text = "U should check this out ASAP! FYI, it's really good. GM!"

In [36]:
def chat_conversation(text):
    for key, value in map.items():
        text = text.replace(key, value)
    return text

In [37]:
print(chat_conversation(text))

You should check this out As Soon As Possible! For Your Information, it's really good. Good Morning!

# 6. Spelling correction

In [38]:
text = "ceertain conditionas duriiing several ggennerations aree modifiedss in the saame manerr."

In [39]:
# pip install textblob

In [40]:
from textblob import TextBlob

In [41]:
textBlb = TextBlob(text)
print(textBlb.correct().string)

certain conditions during several generations are modified in the same manner.

# 7. Removing Stop Words

In [42]:
# !pip install nltk

In [ ]:
# import nltk

# nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\blbon\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [44]:
from nltk.corpus import stopwords

In [102]:
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [45]:
stopwords.words("french")

['au',
 'aux',
 'avec',
 'ce',
 'ces',
 'dans',
 'de',
 'des',
 'du',
 'elle',
 'en',
 'et',
 'eux',
 'il',
 'ils',
 'je',
 'la',
 'le',
 'les',
 'leur',
 'lui',
 'ma',
 'mais',
 'me',
 'même',
 'mes',
 'moi',
 'mon',
 'ne',
 'nos',
 'notre',
 'nous',
 'on',
 'ou',
 'par',
 'pas',
 'pour',
 'qu',
 'que',
 'qui',
 'sa',
 'se',
 'ses',
 'son',
 'sur',
 'ta',
 'te',
 'tes',
 'toi',
 'ton',
 'tu',
 'un',
 'une',
 'vos',
 'votre',
 'vous',
 'c',
 'd',
 'j',
 'l',
 'à',
 'm',
 'n',
 's',
 't',
 'y',
 'été',
 'étée',
 'étées',
 'étés',
 'étant',
 'étante',
 'étants',
 'étantes',
 'suis',
 'es',
 'est',
 'sommes',
 'êtes',
 'sont',
 'serai',
 'seras',
 'sera',
 'serons',
 'serez',
 'seront',
 'serais',
 'serait',
 'serions',
 'seriez',
 'seraient',
 'étais',
 'était',
 'étions',
 'étiez',
 'étaient',
 'fus',
 'fut',
 'fûmes',
 'fûtes',
 'furent',
 'sois',
 'soit',
 'soyons',
 'soyez',
 'soient',
 'fusse',
 'fusses',
 'fût',
 'fussions',
 'fussiez',
 'fussent',
 'ayant',
 'ayante',
 'ayantes',
 'ayants',
 'eu',
 'eue',
 'eues',
 'eus',
 'ai',
 'as',
 'avons',
 'avez',
 'ont',
 'aurai',
 'auras',
 'aura',
 'aurons',
 'aurez',
 'auront',
 'aurais',
 'aurait',
 'aurions',
 'auriez',
 'auraient',
 'avais',
 'avait',
 'avions',
 'aviez',
 'avaient',
 'eut',
 'eûmes',
 'eûtes',
 'eurent',
 'aie',
 'aies',
 'ait',
 'ayons',
 'ayez',
 'aient',
 'eusse',
 'eusses',
 'eût',
 'eussions',
 'eussiez',
 'eussent']

- Hindi stop words are not there in this library

In [46]:
len(stopwords.words('english'))

198

In [47]:
def remove_stopwords(text):
    filtered_words = [word for word in text.split() if word.lower() not in stopwords.words('english')]
    return ' '.join(filtered_words)

In [48]:
df.head()

,sentence,sentence_punctuation,sentence_punctuation_fast
0,where is the bathroom?,where is the bathroom,where is the bathroom
1,i need to use the bathroom.,i need to use the bathroom,i need to use the bathroom
2,can i go to the bathroom?,can i go to the bathroom,can i go to the bathroom
3,the bathroom is on the left.,the bathroom is on the left,the bathroom is on the left
4,"please wait, i am in the bathroom.",please wait i am in the bathroom,please wait i am in the bathroom

In [ ]:
# faster code using sets

from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    filtered_words = [
        word for word in text.split()
        if word.lower() not in stop_words
    ]
    return ' '.join(filtered_words)

In [49]:
df['sentence_no_stopwords'] = df['sentence'].apply(remove_stopwords)

In [50]:
df.head()

,sentence,sentence_punctuation,sentence_punctuation_fast,sentence_no_stopwords
0,where is the bathroom?,where is the bathroom,where is the bathroom,bathroom?
1,i need to use the bathroom.,i need to use the bathroom,i need to use the bathroom,need use bathroom.
2,can i go to the bathroom?,can i go to the bathroom,can i go to the bathroom,go bathroom?
3,the bathroom is on the left.,the bathroom is on the left,the bathroom is on the left,bathroom left.
4,"please wait, i am in the bathroom.",please wait i am in the bathroom,please wait i am in the bathroom,"please wait, bathroom."

# 8. Handling Emojis😂

In [51]:
# two ways of handling emojis in text:
# 1. Remove emojis using regex
# 2. replace emojis with its meaning using emoji library

In [52]:
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [53]:
remove_emoji("Hello 😊! This is a test. 🚀")

'Hello ! This is a test. '

In [54]:
# 2. replace emojis with its meaning using emoji library
# !pip install emoji

In [55]:
import emoji
print(emoji.demojize("Vinod is😊! This is a  🚀"))

Vinod is:smiling_face_with_smiling_eyes:! This is a  :rocket:

In [56]:
print(emoji.demojize("Python is 🔥"))

Python is :fire:

# 9. Tokenization

- 1. Using the split function

In [57]:
# word tokenization
sent1 = "I am going to mumbai"
sent1.split()

['I', 'am', 'going', 'to', 'mumbai']

In [58]:
sent2 = "I am going to Mumbai. I will stay there for 50 days. Let's hope the journey to be great."
sent2.split('.')

['I am going to Mumbai',
 ' I will stay there for 50 days',
 " Let's hope the journey to be great",
 '']

In [59]:
sent3 = "I am going to Mumbai!"
sent3.split()

['I', 'am', 'going', 'to', 'Mumbai!']

In [60]:
# here Mumbai and ! should have been different tokes

In [61]:
sent4 = "Where should I go? I have 50 day holiday"
sent4.split('.')

['Where should I go? I have 50 day holiday']

- 2. Regular expressions

In [62]:
import re
tokens = re.findall("[\w]+", sent3)
tokens

['I', 'am', 'going', 'to', 'Mumbai']

In [63]:
sent3

'I am going to Mumbai!'

- 3. NLTK

In [64]:
# import nltk

# nltk.download('punkt_tab')

In [65]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [66]:
sent3

'I am going to Mumbai!'

In [67]:
word_tokenize(sent3)

['I', 'am', 'going', 'to', 'Mumbai', '!']

In [68]:
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'mumbai']

In [69]:
sent_tokenize(sent2)

['I am going to Mumbai.',
 'I will stay there for 50 days.',
 "Let's hope the journey to be great."]

In [70]:
sent5 = "I have a Ph.D in A.I"
sent6 = "We're here to help! mail us at xyz@gmail.com"
sent7 = "A 500km ride cost $1000"

In [71]:
sent = [sent3, sent5, sent6, sent7]

In [72]:
for sentence in sent:
  print(f"{sentence}:{word_tokenize(sentence)}")

I am going to Mumbai!:['I', 'am', 'going', 'to', 'Mumbai', '!']
I have a Ph.D in A.I:['I', 'have', 'a', 'Ph.D', 'in', 'A.I']
We're here to help! mail us at xyz@gmail.com:['We', "'re", 'here', 'to', 'help', '!', 'mail', 'us', 'at', 'xyz', '@', 'gmail.com']
A 500km ride cost $1000:['A', '500km', 'ride', 'cost', '$', '1000']

- 4. using spacy

In [73]:
# !pip install spacy

In [74]:
# !python -m spacy download en_core_web_sm

In [77]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [78]:
doc = []
for sentence in sent:
  doc.append(nlp(sentence))

In [79]:
doc

[I am going to Mumbai!,
 I have a Ph.D in A.I,
 We're here to help! mail us at xyz@gmail.com,
 A 500km ride cost $1000]

In [80]:
for d in doc:
  print(f"{d}:")
  for token in d:
    print(token)

I am going to Mumbai!:
I
am
going
to
Mumbai
!
I have a Ph.D in A.I:
I
have
a
Ph
.
D
in
A.I
We're here to help! mail us at xyz@gmail.com:
We
're
here
to
help
!
mail
us
at
xyz@gmail.com
A 500km ride cost $1000:
A
500
km
ride
cost
$
1000

**Conclusion:- SpaCy is performing good, but if we have simple dataset we can use nltk**

# 10. Stemming

In [81]:
from nltk.stem.porter import PorterStemmer

In [82]:
ps = PorterStemmer()
def stem_words(text):
  return " ".join([ps.stem(word) for word in text.split()])

In [83]:
sample = "walk walks walking walked"

In [84]:
stem_words(sample)

'walk walk walk walk'

In [85]:
text = "probably my alltime favorite movie is story of selflessness sacrifice."

In [86]:
print(text)
print(stem_words(text))

probably my alltime favorite movie is story of selflessness sacrifice.
probabl my alltim favorit movi is stori of selfless sacrifice.

# 11. Lemmatization

In [87]:
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

In [88]:
sentence = "He was running and eating at same time. He had bad habit of swimming after playing long hours in the Sun."

In [89]:
tokens = word_tokenize(sentence)

In [90]:
tokens

['He',
 'was',
 'running',
 'and',
 'eating',
 'at',
 'same',
 'time',
 '.',
 'He',
 'had',
 'bad',
 'habit',
 'of',
 'swimming',
 'after',
 'playing',
 'long',
 'hours',
 'in',
 'the',
 'Sun',
 '.']

In [91]:
import string
punctuations = string.punctuation

In [92]:
punctuations

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [93]:
for token in tokens:
  if token in punctuations:
    tokens.remove(token)

In [94]:
# import nltk

# nltk.download('wordnet')

In [95]:
print("{0:20}{1:20}".format("Word", "Lemma"))
for token in tokens:
  print("{0:20}{1:20}".format(token, wordnet_lemmatizer.lemmatize(token, pos = "v")))

Word                Lemma
He                  He
was                 be
running             run
and                 and
eating              eat
at                  at
same                same
time                time
He                  He
had                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
Sun                 Sun

## Assignment :
- Create a dataset of movies , with three features movie name, descriptiona and genre
- use APIs for data fetching
- https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=471
- https://api.themoviedb.org/3/genre/movie/list?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US
- after that do the text preprocessing

- for creating dataset see Day-1, Data_Acquisition notebook

In [104]:
df_mov = pd.read_csv("../Day-1/movies.csv")

In [106]:
df_mov.head()

,Unnamed: 0,movie_name,description,genre
0,0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"Drama, Crime"
1,1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama, Crime"
2,2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"Drama, Crime"
3,3,Schindler's List,The true story of how businessman Oskar Schind...,"Drama, History, War"
4,4,12 Angry Men,The defense and the prosecution have rested an...,Drama

In [107]:
df_mov.columns

Index(['Unnamed: 0', 'movie_name', 'description', 'genre'], dtype='object')

In [108]:
df_mov.drop(columns=['Unnamed: 0'], inplace=True)

In [110]:
df_mov.head()

,movie_name,description,genre
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"Drama, Crime"
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama, Crime"
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"Drama, Crime"
3,Schindler's List,The true story of how businessman Oskar Schind...,"Drama, History, War"
4,12 Angry Men,The defense and the prosecution have rested an...,Drama

In [111]:
df_mov.shape

(40, 3)