<h1>Basic Preprocessing:</h1>

<strong>Preprocessing on movies.csv file that we have created in DATA-Acquisition step</strong>

In [2]:
import pandas as pd
import numpy as np
import re

import warnings
warnings.filterwarnings("ignore")

In [3]:
df = pd.read_csv("../03-Data-Acquisition/movies.csv")

In [4]:
df.head()

   Unnamed: 0  ...                genre
0           0  ...         Drama, Crime
1           1  ...         Drama, Crime
2           2  ...         Drama, Crime
3           3  ...  Drama, History, War
4           4  ...                Drama

[5 rows x 4 columns]

In [5]:
df.movie_name.tail()

35      A Silent Voice: The Movie
36    Once Upon a Time in America
37                          Se7en
38              Gabriel's Inferno
39                       Whiplash
Name: movie_name, dtype: object

# 1 Lowercasing

In [6]:
df.movie_name[0].lower()

'the shawshank redemption'

In [7]:
df['movie_name'] = df['movie_name'].str.lower()

In [8]:
df.head()

   Unnamed: 0  ...                genre
0           0  ...         Drama, Crime
1           1  ...         Drama, Crime
2           2  ...         Drama, Crime
3           3  ...  Drama, History, War
4           4  ...                Drama

[5 rows x 4 columns]

<h1>2 Extra White Spaces:</h1>

In [9]:
text = "  movie    name   "
print(text.strip()) # remove only trailing spaces
print(" ".join(text.split()))

movie    name
movie name

In [10]:
def remove_extra_spaces(text):
    return " ".join(text.split())

In [11]:
# use RegEx to remove white spaces , it is faster than other method

pattern = r'\s+'
# print(re.sub(pattern, " ", text))
def remove_extra_spaces(text):
    return re.sub(pattern, " ", text).strip()
remove_extra_spaces(text)

'movie name'

In [12]:
df['movie_name'] = df['movie_name'].apply(remove_extra_spaces)

In [13]:
# but we have to be very carefull since it is slow process
# use RegEx

<h1>3 Handling Numbers:</h1>

In [14]:
text = "I have 2 movie dataset and 1 company dataset"
import re
pattern = re.compile(r'\d+')
print(re.sub(pattern, "", text))

I have  movie dataset and  company dataset

In [15]:
# pip install num2words

In [16]:
from num2words import num2words

print(num2words(88))
print(num2words(125))

eighty-eight
one hundred and twenty-five

In [17]:
# convert numbers with corresponding word
def numbers_to_word(text):
    result = []
    for word in text.split():
        if word.isdigit():
            result.append(num2words(word))
        else:
            result.append(word)
    return " ".join(result)

In [18]:
print(numbers_to_word("I don't have 99 rupees"))

I don't have ninety-nine rupees

In [19]:
df['movie_name'] = df.movie_name.apply(numbers_to_word)

In [20]:
df.head()

   Unnamed: 0  ...                genre
0           0  ...         Drama, Crime
1           1  ...         Drama, Crime
2           2  ...         Drama, Crime
3           3  ...  Drama, History, War
4           4  ...                Drama

[5 rows x 4 columns]

- **In this number handling it doesn't handle these words like "Se7en".**
- **For this we can apply character by character instead of word by word checking.**

<h1>4 Remove HTML Tag :</h1>

- since this movies.csv is made using APIs so it is less probable to have HTML tag
- But in our dataset ambitionbox_company_data might have HTML tag since it is made using Web Scraping

In [21]:
text = """
    <html>
    <head>
    <title>My Website</title>
    </head>

    <body>

    <h1>Welcome to AI World</h1>

    <p>This is a <b>machine learning</b> tutorial.</p>

    <a href="https://example.com">Click Here</a>

    <div>
        <p>Deep Learning and NLP are trending fields.</p>
    </div>

    </body>
    </html>

"""

In [22]:
pattern = r'<.*?>'
cleaned_text  = re.sub(pattern, '', text)
cleaned_text

'\n    \n    \n    My Website\n    \n\n    \n\n    Welcome to AI World\n\n    This is a machine learning tutorial.\n\n    Click Here\n\n    \n        Deep Learning and NLP are trending fields.\n    \n\n    \n    \n\n'

In [23]:
print(cleaned_text.strip())

My Website




    Welcome to AI World

    This is a machine learning tutorial.

    Click Here


        Deep Learning and NLP are trending fields.

In [24]:
# here so many spaces are there
# 1. use split function then join
# 2. use regex 

pattern = r'\s+'
print(re.sub(pattern, ' ', cleaned_text))

 My Website Welcome to AI World This is a machine learning tutorial. Click Here Deep Learning and NLP are trending fields.

In [25]:
pattern1 = re.compile(r'<.*?>') # remove HTML tags
pattern2 = re.compile(r'\s+') # remove white spaces
def remove_HTML_tag(text):
    return re.sub(pattern2, ' ', re.sub(pattern1, '', text)).strip()

In [26]:
print(remove_HTML_tag(text))

My Website Welcome to AI World This is a machine learning tutorial. Click Here Deep Learning and NLP are trending fields.

In [27]:
# df.movie_name = df.movie_name.apply(remove_HTML_tag)
# can be applied wherever needed

# 5 Remove and Extract URLs, Email addresses and HashTags

In [28]:
text = """
    Hello everyone!

    Visit our website at https://www.vinod-codes-ai.com for more information.

    You can also check:
    http://vinod-codes-nlp.com/blog
"""

In [29]:
pattern = re.compile(r'https?://\S+|www\.\S+')
print(re.findall(pattern, text))
print(re.sub(pattern, "URL", text))
print(re.sub(r'\s+', " ", re.sub(pattern, "", text))) # It works fine if text has urls else it will nail you down

['https://www.vinod-codes-ai.com', 'http://vinod-codes-nlp.com/blog']

    Hello everyone!

    Visit our website at URL for more information.

    You can also check:
    URL

 Hello everyone! Visit our website at for more information. You can also check:

In [30]:
pattern_url = r'https?://\S+|www\.\S+'
pattern_rem_space = r'\s+'
def remove_URLs(text):
    # return re.sub(r'\s+', " ", re.sub(pattern, "URL", text)).strip()  # don't do this it will nail you 
    # do this
    text1 = re.sub(pattern_url, "URL", text)
    return re.sub(r'\s+', " ", text1).strip()

In [31]:
text = "movie   name    "
remove_URLs(text)

'movie name'

In [32]:
df.movie_name = df.movie_name.apply(remove_URLs)

In [33]:
df.head()
df.tail()

    Unnamed: 0  ...                      genre
35          35  ...  Animation, Drama, Romance
36          36  ...               Drama, Crime
37          37  ...   Crime, Mystery, Thriller
38          38  ...             Romance, Drama
39          39  ...     Drama, Music, Thriller

[5 rows x 4 columns]

In [34]:
def extract_URLs(text):
    return re.findall(pattern_url, text)

In [35]:
df['urls'] = df.movie_name.apply(extract_URLs)

In [36]:
# no urls
df.drop(columns  = ["urls"], axis = 1, inplace = True)

In [37]:
df.columns

Index(['Unnamed: 0', 'movie_name', 'description', 'genre'], dtype='object')

In [38]:
import re

text = "Visit http://vinod-codes-ai.com for more info. Contact us at prajapatvinodkumar18@gmail.com #AI"


processed_text = re.sub(pattern_url, 'URL', text)  
print("URL:",re.findall(pattern_url, text))
processed_text = re.sub(r'\S+@\S+', 'EMAIL', processed_text) 
print("EMAIL:",re.findall(r'\S+@\S+', text))

# Replace hashtags with 'HASHTAG' followed by the content
processed_text = re.sub(r'#(\S+)', r'HASHTAG \1', processed_text)  # Keep word after #

print(processed_text)

URL: ['http://vinod-codes-ai.com']
EMAIL: ['prajapatvinodkumar18@gmail.com']
Visit URL for more info. Contact us at EMAIL HASHTAG AI

# 6 Remove Punctuations:

In [39]:
import string
exclude = string.punctuation
print("Punctuations are:",exclude)

Punctuations are: !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~

In [40]:
def remove_punctuation(text):
    for char in exclude:
        text = text.replace(char, "")
    return text

In [41]:
print(remove_punctuation("hello i am vinod. Learning NLP but why?"))

hello i am vinod Learning NLP but why

In [42]:
import time
start = time.time()
df['movie_name_1'] = df.movie_name.apply(remove_punctuation)
end = time.time()
time1 = end-start
print("time taken in algorith:", time1,"s")

time taken in algorith: 0.0 s

In [43]:
df.head()

   Unnamed: 0  ...              movie_name_1
0           0  ...  the shawshank redemption
1           1  ...             the godfather
2           2  ...     the godfather part ii
3           3  ...           schindlers list
4           4  ...          twelve angry men

[5 rows x 5 columns]

In [44]:
# using standard library to remove punctuations
def remove_punctuation_fast(text):
    return text.translate(str.maketrans("", "", exclude))

In [45]:
print(remove_punctuation_fast("hello i am vinod. Learning NLP but why?"))

hello i am vinod Learning NLP but why

In [46]:
import time
start = time.time()
df['movie_name'] = df.movie_name.apply(remove_punctuation_fast)
end = time.time()
time2 = end-start
print("time taken in algorith:", time1,"s")

time taken in algorith: 0.0 s

In [47]:
time2 < time1

False

In [48]:
# in huge dataset this time difference (time2 - time1) will be significant
# so use this second method

In [49]:
df.drop(columns = ["movie_name_1"], axis = 1, inplace = True)
df.head()

   Unnamed: 0  ...                genre
0           0  ...         Drama, Crime
1           1  ...         Drama, Crime
2           2  ...         Drama, Crime
3           3  ...  Drama, History, War
4           4  ...                Drama

[5 rows x 4 columns]

In [50]:
# we can use contraction as well

In [51]:
# !pip install contractions

# import contractions

# # Sample text with contractions
# text = "I don't like coding at night."

# # Expand contractions
# expanded_text = contractions.fix(text)
# print(expanded_text)

# output:- I do not like coding at night.

# 7 Chat word treatment

- used on social media generated dataset

- when u chat on social media :-

- u : you
- FYI : for your information
- GN : good night
- GM : good morning

In [52]:
map = {
    "U":"You",
    "FYI":"For Your Information",
    "GM":"Good Morning",
    "ASAP":"As Soon As Possible"
}

In [53]:
def chat_conversation(text):
    for key, value in map.items():
        text = text.replace(key, value)
    return text

In [54]:
text = "U should check this out ASAP! FYI, it's really good. GM!"
print(chat_conversation(text))

You should check this out As Soon As Possible! For Your Information, it's really good. Good Morning!

# 8 Spelling correction

In [55]:
text = "ceertain conditionas duriiing several ggennerations aree modifiedss in the saame manerr."

In [56]:
from textblob import TextBlob
textBlb = TextBlob(text)
print(textBlb.correct().string)

certain conditions during several generations are modified in the same manner.

In [57]:
def correct_spell(text):
    return TextBlob(text).correct().string

In [58]:
correct_spell(text)

'certain conditions during several generations are modified in the same manner.'

In [59]:
df['movie_name'] = df['movie_name'].apply(correct_spell)

In [60]:
# it takes more time so use whenever needed

In [61]:
# # second method:
# !pip install pyspellchecker
# from spellchecker import SpellChecker

# # Sample text with spelling mistakes
# text = "I recieved a messsage."

# # Correct spelling
# spell = SpellChecker()
# words = text.split()
# corrected_text = " ".join([spell.correction(word) for word in words])
# print(corrected_text)

# 9 Handling Emojis😂

- used when we handle social media dataset

In [62]:
# two ways of handling emojis in text:
# 1. Remove emojis using regex
# 2. replace emojis with its meaning using emoji library

In [63]:
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [64]:
remove_emoji("Hello 😊! This is a test. 🚀")

'Hello ! This is a test. '

In [65]:
# 2. replace emojis with its meaning using emoji library
# !pip install emoji

In [66]:
import emoji
print(emoji.demojize("Vinod is😊! This is a  🚀"))
print(emoji.demojize("Python is 🔥"))

Vinod is:smiling_face_with_smiling_eyes:! This is a  :rocket:
Python is :fire:

# 10 Removing Stop Words

In [67]:
# !pip install nltk
# import nltk
# nltk.download("stopwords")

In [68]:
from nltk.corpus import stopwords
print(stopwords.words("english"))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

In [69]:
print(stopwords.words("french"))

['au', 'aux', 'avec', 'ce', 'ces', 'dans', 'de', 'des', 'du', 'elle', 'en', 'et', 'eux', 'il', 'ils', 'je', 'la', 'le', 'les', 'leur', 'lui', 'ma', 'mais', 'me', 'même', 'mes', 'moi', 'mon', 'ne', 'nos', 'notre', 'nous', 'on', 'ou', 'par', 'pas', 'pour', 'qu', 'que', 'qui', 'sa', 'se', 'ses', 'son', 'sur', 'ta', 'te', 'tes', 'toi', 'ton', 'tu', 'un', 'une', 'vos', 'votre', 'vous', 'c', 'd', 'j', 'l', 'à', 'm', 'n', 's', 't', 'y', 'été', 'étée', 'étées', 'étés', 'étant', 'étante', 'étants', 'étantes', 'suis', 'es', 'est', 'sommes', 'êtes', 'sont', 'serai', 'seras', 'sera', 'serons', 'serez', 'seront', 'serais', 'serait', 'serions', 'seriez', 'seraient', 'étais', 'était', 'étions', 'étiez', 'étaient', 'fus', 'fut', 'fûmes', 'fûtes', 'furent', 'sois', 'soit', 'soyons', 'soyez', 'soient', 'fusse', 'fusses', 'fût', 'fussions', 'fussiez', 'fussent', 'ayant', 'ayante', 'ayantes', 'ayants', 'eu', 'eue', 'eues', 'eus', 'ai', 'as', 'avons', 'avez', 'ont', 'aurai', 'auras', 'aura', 'aurons', 'aurez', 'auront', 'aurais', 'aurait', 'aurions', 'auriez', 'auraient', 'avais', 'avait', 'avions', 'aviez', 'avaient', 'eut', 'eûmes', 'eûtes', 'eurent', 'aie', 'aies', 'ait', 'ayons', 'ayez', 'aient', 'eusse', 'eusses', 'eût', 'eussions', 'eussiez', 'eussent']

In [70]:
# stopwords.words("hindi") 
# hindi stop words are not available

In [71]:
def remove_stopwords(text):
    filtered_words = [word for word in text.split() if word.lower() not in stopwords.words("english")]
    return " ".join(filtered_words)

In [72]:
remove_stopwords("hindi stop words ARE not available")

'hindi stop words available'

In [73]:
import time
start = time.time()
df['movie_name_1'] = df.movie_name.apply(remove_stopwords)
end = time.time()
time1 = end - start

In [74]:
# faster code using sets
stop_words = set(stopwords.words('english'))
def remove_stopwords_fast(text):
    filtered_words = [word for word in text.split() if word.lower() not in stop_words]
    return " ".join(filtered_words)

In [75]:
remove_stopwords_fast("hindi stop words ARE not available")

'hindi stop words available'

In [76]:
import time
start = time.time()
df['movie_name'] = df.movie_name.apply(remove_stopwords_fast)
end = time.time()
time2 = end - start

In [77]:
print(f"second algorithm is {time1 - time2}s faster than first one")

second algorithm is 0.1333904266357422s faster than first one

In [78]:
df.drop(columns = ['movie_name_1'], axis = 1, inplace = True)

In [79]:
df.head()

   Unnamed: 0  ...                genre
0           0  ...         Drama, Crime
1           1  ...         Drama, Crime
2           2  ...         Drama, Crime
3           3  ...  Drama, History, War
4           4  ...                Drama

[5 rows x 4 columns]

# 11. Tokenization

## a. Using Split Function

In [80]:
# word tokenization
sent1 = "I am going to mumbai"
sent1.split()

['I', 'am', 'going', 'to', 'mumbai']

In [81]:
# sentence tokenization
sent2 = "I am going to Mumbai. I will stay there for 50 days. Let's hope the journey to be great."
sent2.split('.')

['I am going to Mumbai',
 ' I will stay there for 50 days',
 " Let's hope the journey to be great",
 '']

In [82]:
sent3 = "I am going to Mumbai!"
sent3.split()

['I', 'am', 'going', 'to', 'Mumbai!']

- here Mumbai and ! should have been different tokes

In [83]:
sent4 = "Where should i go? I have 50 days holiday"
print(sent4.split())
print(sent4.split('.'))

['Where', 'should', 'i', 'go?', 'I', 'have', '50', 'days', 'holiday']
['Where should i go? I have 50 days holiday']

## b. Using RegEx

In [84]:
import re
tokens = re.findall('[\w]+', sent3)
print(tokens)

['I', 'am', 'going', 'to', 'Mumbai']

## c. NLTK

In [85]:
# import nltk
# nltk.download("plunkt_tab")

In [86]:
from nltk.tokenize import word_tokenize, sent_tokenize

In [87]:
print(word_tokenize(sent3))
print(sent_tokenize(sent2))
print(word_tokenize(sent2))

['I', 'am', 'going', 'to', 'Mumbai', '!']
['I am going to Mumbai.', 'I will stay there for 50 days.', "Let's hope the journey to be great."]
['I', 'am', 'going', 'to', 'Mumbai', '.', 'I', 'will', 'stay', 'there', 'for', '50', 'days', '.', 'Let', "'s", 'hope', 'the', 'journey', 'to', 'be', 'great', '.']

In [88]:
sent5 = "I have a Ph.D in A.I"
sent6 = "We're here to help! mail us at xyz@gmail.com"
sent7 = "A 500km ride cost $1000"

sent = [sent3, sent5, sent6, sent7]
for sentence in sent:
  print(f"{sentence}:{word_tokenize(sentence)}")

I am going to Mumbai!:['I', 'am', 'going', 'to', 'Mumbai', '!']
I have a Ph.D in A.I:['I', 'have', 'a', 'Ph.D', 'in', 'A.I']
We're here to help! mail us at xyz@gmail.com:['We', "'re", 'here', 'to', 'help', '!', 'mail', 'us', 'at', 'xyz', '@', 'gmail.com']
A 500km ride cost $1000:['A', '500km', 'ride', 'cost', '$', '1000']

## d. Using SpaCy Library

In [89]:
# !pip install spacy
# !python -m spacy download en_core_web_sm

In [90]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [91]:
doc = []
for sentence in sent:
    doc.append(nlp(sentence))
print(doc)

[I am going to Mumbai!, I have a Ph.D in A.I, We're here to help! mail us at xyz@gmail.com, A 500km ride cost $1000]

In [92]:
for d in doc:
  print(f"{d}:")
  for token in d:
    print(token)

I am going to Mumbai!:
I
am
going
to
Mumbai
!
I have a Ph.D in A.I:
I
have
a
Ph
.
D
in
A.I
We're here to help! mail us at xyz@gmail.com:
We
're
here
to
help
!
mail
us
at
xyz@gmail.com
A 500km ride cost $1000:
A
500
km
ride
cost
$
1000

**Conclusion:- SpaCy is performing good, but if we have simple dataset we can use nltk**

# 12. Stemming

In [93]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [94]:
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [95]:
sample = "walk walks walking walked"
print(stem_words(sample))
text = "probably my alltime favorite movie is story of selflessness sacrifice."
print(stem_words(text))

walk walk walk walk
probabl my alltim favorit movi is stori of selfless sacrifice.

- Here words not in natural verb

# 13. Lemmatization

- use when we need to show the result to someone. else use stemming since that is faster than Lemmatization

In [96]:
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

In [97]:
# import nltk

# nltk.download('wordnet')

In [98]:
sample = "walk walks walking walked"
tokens1 = word_tokenize(sample)
text = "probably my alltime favorite movie is story of selflessness sacrifice."
tokens2 = word_tokenize(text)

In [99]:
import string
punctuations = string.punctuation

In [100]:
for token in tokens1:
  if token in punctuations:
    tokens1.remove(token)

In [101]:
for token in tokens2:
  if token in punctuations:
    tokens2.remove(token)

In [102]:
print(tokens1)
print(tokens2)

['walk', 'walks', 'walking', 'walked']
['probably', 'my', 'alltime', 'favorite', 'movie', 'is', 'story', 'of', 'selflessness', 'sacrifice']

In [103]:
print("{0:20}{1:20}".format("Word", "Lemma"))
for token in tokens1:
  print("{0:20}{1:20}".format(token, wordnet_lemmatizer.lemmatize(token, pos = "v")))

Word                Lemma
walk                walk
walks               walk
walking             walk
walked              walk

In [104]:
print("{0:20}{1:20}".format("Word", "Lemma"))
for token in tokens2:
  print("{0:20}{1:20}".format(token, wordnet_lemmatizer.lemmatize(token, pos = "v")))

Word                Lemma
probably            probably
my                  my
alltime             alltime
favorite            favorite
movie               movie
is                  be
story               story
of                  of
selflessness        selflessness
sacrifice           sacrifice

## Assignment :
- Create a dataset of movies , with three features movie name, descriptiona and genre
- use APIs for data fetching
- https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=471
- https://api.themoviedb.org/3/genre/movie/list?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US
- after that do the text preprocessing

- <a>Note:  </a>for creating dataset see  Data_Acquisition notebook

# Advance Text-Preprocessing

## 1. POS Tagging

- Parts of speech tagging
- it is a preprocessing step in text preprocessing
- it is a task of labelling each word in a sentence with it's appropriate parts of speech
- POS is a category of words that have similar grammatical properties
- ex.. Will will search blogs. here will --> Modal, will --> Noun, search --> Verb and blogs --> Noun
- <p>In  <span style = "background-color:red; color:white">I left<span> the room and <span style = "background-color:red; color:white">left<span> of the room<p>
- both left carry diffferent meaning

<strong>Applications of POS tagging</strong>
1. Named entity recognition used in retrieval system.
2. Question answering system
3. Word sense disambiguation --> i left the room and left of the room , here left has different context in both the sentences
4. chatbots

<strong>We do Part-of-Speech (POS) tagging because it helps a computer understand how words function in a sentence—not just what they mean individually, but how they relate to each other.</strong>

<strong>POS Tagging using nltk:</strong>

In [106]:
import nltk
from nltk import pos_tag

# nltk.download('averaged_perceptron_tagger_eng')

In [112]:
text = "Will Will search my blogs"
tokens = word_tokenize(text)
tagged = pos_tag(tokens)
for tag in tagged:
    print(tag)

('Will', 'MD')
('Will', 'NNP')
('search', 'VB')
('my', 'PRP$')
('blogs', 'NNS')

In [125]:
text = "left of the room"
tokens = word_tokenize(text)
tagged = pos_tag(tokens)
for tag in tagged:
    print(tag)

('left', 'NN')
('of', 'IN')
('the', 'DT')
('room', 'NN')

**Excellent result**

<strong>Using SpaCy Library:</strong>

In [113]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [117]:
doc = nlp(text)
print(doc)
for word in doc:
    print(word, "-->", word.pos_, word.tag_, spacy.explain(word.tag_))

Will Will search my blogs
Will --> AUX MD verb, modal auxiliary
Will --> AUX MD verb, modal auxiliary
search --> VERB VB verb, base form
my --> PRON PRP$ pronoun, possessive
blogs --> NOUN NNS noun, plural

In [122]:
for word in nlp("left of the room."):
    print(word, "-->", word.tag_, spacy.explain(word.tag_))

left --> VBN verb, past participle
of --> IN conjunction, subordinating or preposition
the --> DT determiner
room --> NN noun, singular or mass
. --> . punctuation mark, sentence closer

**nltk is giving good results**

In [118]:
# visualization
from spacy import displacy
displacy.render(doc, style="dep", jupyter=True)

In [119]:
options = {
    "distance":90,
    "compact":True,
    "color":"red",
    "bg":"white"
}
displacy.render(doc, style="dep", jupyter=True, options=options)

<b>This is because we did aggressive text preprocessing , converted into lowercase, removed stop words</b>
<br>
<u>Text preprocessing is a task specific</u>

### How POS tagging works

- Hidden Markov model (HMM) is used to do this task
- it is very expensive so , to optimize it , <b>Viterbi algorithm is used</b>

## 2. NER

In [1]:
import spacy

nlp = spacy.load("en_core_web_sm")

text = "Google wes founded by Larry Page and Sergey Brin."

In [2]:
doc = nlp(text)
print(doc.text)
tokens = []
for token in doc:
    tokens.append(token.text)
NER = []
for token in doc.ents:
    NER.append((token.text, token.label_))
    
print(tokens)
print(NER)

Google wes founded by Larry Page and Sergey Brin.
['Google', 'wes', 'founded', 'by', 'Larry', 'Page', 'and', 'Sergey', 'Brin', '.']
[('Google', 'ORG'), ('Larry Page', 'PERSON'), ('Sergey Brin', 'PERSON')]

In [3]:
for entity in NER:
    print(f"{entity[0]} : {entity[1]} : {spacy.explain(entity[1])}")

Google : ORG : Companies, agencies, institutions, etc.
Larry Page : PERSON : People, including fictional
Sergey Brin : PERSON : People, including fictional

## 3. Parsing

- Parsing means analyzing the grammatical structure of a sentence.
- It determines:
    *  which word connects to which
    * subject
    * object
    * modifiers
    * phrase structure

**Example:**
- “Dog bites man”
<br>
and
<br>
- “Man bites dog”

- Here POS tagging will give same tags in both the sentences but it doesn't mean that meaning is same.
- Parsing identifies:
    * who performed the action
    * who received the action

## 4. Coreference Resolution

- Coreference resolution means finding which words or phrases refer to the same real-world entity in a text.

**Ex.**
- “Rahul went to the store. He bought milk.”

- Here:
    * Rahul
    * He
- refer to the same person.
- The NLP system must understand that “He” = “Rahul”.
- Humans naturally understand references, but computers do not.