# <h1>DATA ACQUISITION</h1>

<h1>1. Starting with Json data</h1>

In [2]:
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

In [4]:
df = pd.read_json("test.json")

In [5]:
df.head()

      id                                        ingredients
0  18009  [baking powder, eggs, all-purpose flour, raisi...
1  28583  [sugar, egg yolks, corn starch, cream of tarta...
2  41580  [sausage links, fennel bulb, fronds, olive oil...
3  29752  [meat cuts, file powder, smoked sausage, okra,...
4  35687  [ground black pepper, salt, sausage casings, l...

In [6]:
df.columns

Index(['id', 'ingredients'], dtype='object')

In [7]:
df.ingredients[0][0]

'baking powder'

In [8]:
#df = pd.read_json(url)

**Conclusion : json to dataframe , now u can apply EDA or all the step**

# 2. SQL data

In [ ]:
# !pip install mysql.connector
# run this if not installed

Requirement already satisfied: mysql.connector in c:\users\blbon\desktop\myworkspace\tech\nlp\nlp\lib\site-packages (2.2.9)

In [13]:
import mysql.connector

In [14]:
conn = mysql.connector.connect(host = 'localhost', user = 'root', password = '', database = 'world')

In [15]:
pd.read_sql_query("SHOW TABLES", conn)

   Tables_in_world
0             city
1          country
2  countrylanguage

In [16]:
df_city = pd.read_sql_query("SELECT * FROM city", conn)

In [17]:
df_city.head()

   ID            Name CountryCode       District  Population
0   1           Kabul         AFG          Kabol     1780000
1   2        Qandahar         AFG       Qandahar      237500
2   3           Herat         AFG          Herat      186800
3   4  Mazar-e-Sharif         AFG          Balkh      127800
4   5       Amsterdam         NLD  Noord-Holland      731200

In [18]:
df_country = pd.read_sql_query("SELECT * FROM country", conn)

In [19]:
df_country.head()

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,Code2
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,AW
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,AF
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,AO
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,AI
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,AL

# 3. Data acquisition using APIs

API :- application programming interface, used to interface two software or it is a data pipeline

In [20]:
# use rapid api to get data from api and convert it to dataframe

In [21]:
# !pip install requests

In [3]:
import requests

url = "https://imdb232.p.rapidapi.com/api/actors/get-related-news"

querystring = {"limit":"25","nm":"nm0366389"}

headers = {
	"x-rapidapi-key": "2d47fc40b3msh5a8e62db2fa524fp1439dfjsn44bc58ccf4d0",
	"x-rapidapi-host": "imdb232.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers, params=querystring)

print(response.json())

{'data': {'name': {'id': 'nm0366389', 'nameText': {'text': 'Kevin Hart'}, 'news': {'__typename': 'NewsConnection', 'edges': [{'node': {'__typename': 'News', 'id': 'ni65852252', 'byline': 'David Niederhoffer', 'date': '2026-05-22T06:11:47Z', 'externalUrl': 'https://www.justjared.com/2026/05/22/brad-pitt-jacob-elordi-more-attend-mercedes-amgs-car-reveal-on-los-angeles-6th-street-bridge/', 'articleTitle': {'plainText': 'Brad Pitt, Jacob Elordi, & More Attend Mercedes-amg’s Car Reveal on Los Angeles’ 6th Street Bridge'}, 'image': {'__typename': 'Image', 'id': 'rm740216322', 'url': 'https://m.media-amazon.com/images/M/MV5BMGUxZDkxYWQtMDVjYi00NmZjLWJlYzItNjcyODE5OTYzOGZkXkEyXkFqcGc@._V1_.jpg', 'height': 675, 'width': 1200}, 'text': {'plainText': 'Mercedes-Benz Amg\n\nMercedes-amg launched a new car in the most epic way – with a huge production on Los Angeles’ 6th Street Bridge and with lots of A-List talent in attendance!\n\nThe car company shut down the bridge on Tuesday night (May 19) for the reveal of the Amg Gt 4-Door Coupe.\n\nBrad Pitt, Jacob Elordi, Kourtney Kardashian and Travis Barker, Kevin Hart, Odell Beckham Jr., Olympic medalist Miles Chamley-Watson, fashion tastemaker Rahi Chadda, and Mercedes’ Formula One drivers George Russell and Kimi Antonelli were among the stars who were there.\n\nMercedes’ chief marketing officer Melody Lee told THR that Brad was paid to be there.\n\n“That’s a paid partnership. I can be upfront about that,'}, 'source': {'homepage': {'url': 'https://www.justjared.com/', 'label': 'Just Jared'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65851413', 'byline': 'Brett Berk', 'date': '2026-05-21T18:07:35Z', 'externalUrl': 'https://www.hollywoodreporter.com/lifestyle/lifestyle-news/brad-pitt-mercedes-6th-street-german-autobahn-1236603553/', 'articleTitle': {'plainText': 'How Brad Pitt and Mercedes Transformed L.A.’s 6th Street Viaduct into a German Autobahn'}, 'image': {'__typename': 'Image', 'id': 'rm2315963906', 'url': 'https://m.media-amazon.com/images/M/MV5BYzIyYzdjMjgtNDlhYy00ZjI0LThlMjktMWM3ZmRmY2UxMTI1XkEyXkFqcGc@._V1_.jpg', 'height': 200, 'width': 200}, 'text': {'plainText': 'A tennis ball yellow car ripped across the Sixth Street Bridge in a cloud of tire smoke on Tuesday night. But unlike the traditional hot rods, drag racers, and lowriders that have long made this L.A. River crossing famed among Angeleno automotive enthusiasts, and as a filming location in movies like Grease and Terminator 2, it did so without a honking gasoline-powered engine. Additionally atypical, the span was closed to public traffic and outfitted with signage that suggested it was part of the German Autobahn. Also, when the car’s occupants emerged, one was Brad Pitt.\n\nThe star was reprising a role, of sorts, that of Sonny Hayes, the redemption-seeking racecar driver from 2025’s smash hit F1. This was based not just on the car’s speed and attention-grabbing stunting, but because the company backing Pitt in both instances is the same: Mercedes-Benz. The German luxury automaker was the'}, 'source': {'homepage': {'url': 'http://www.hollywoodreporter.com/topic/movies', 'label': 'The Hollywood Reporter - Movie News'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65850938', 'byline': 'Nolan Strong', 'date': '2026-05-21T13:00:09Z', 'externalUrl': 'https://allhiphop.com/news/chelsea-handler-destroys-racists-shane-gillis-tony-hinchcliffe-over-kevin-hart-roast/', 'articleTitle': {'plainText': 'Chelsea Handler Destroys “Racists” Shane Gillis & Tony Hinchcliffe Over Kevin Hart Roast'}, 'image': {'__typename': 'Image', 'id': 'rm2386546178', 'url': 'https://m.media-amazon.com/images/M/MV5BNTZkN2I5ZDItMmQzNy00OWE4LTg0YjgtMTVmNWFhOTc1YWRhXkEyXkFqcGc@._V1_.jpg', 'height': 800, 'width': 1200}, 'text': {'plainText': 'Chelsea Handler went nuclear on the Netflix roast stage and then took it even further during a podcast appearance, calling out Shane Gillis and Tony Hinchcliffe for crossing every line that exists.\n\nShe didn’t hold back when she appeared on Deon Cole’s Funny Knowing You podcast, where she made it crystal clear what she thought about their material.\n\n“I knew enough about Tony and Shane, they’re racists, they’re bigots, they’re sexist,” Handler said without any filter whatsoever. “I don’t find those jokes funny. Lynching Black people is not a joke. It’s worse than rape.”\n\nThe roast itself became a minefield of offensive content,'}, 'source': {'homepage': {'url': 'https://allhiphop.com/tag/hollywood/', 'label': 'AllHipHop'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65851114', 'byline': 'Kim Brown', 'date': '2026-05-21T12:47:29Z', 'externalUrl': 'https://www.justjared.com/2026/05/21/chelsea-handler-slams-shane-gillis-tony-hinchcliffe-as-racist-sexist/', 'articleTitle': {'plainText': 'Chelsea Handler Slams Shane Gillis & Tony Hinchcliffe as ‘Racist’ & ‘Sexist’'}, 'image': {'__typename': 'Image', 'id': 'rm3375615490', 'url': 'https://m.media-amazon.com/images/M/MV5BMWM3NjNiYTctYjhlZC00N2UyLWExMjYtNzc0Mzk3YjkyNTMwXkEyXkFqcGc@._V1_.jpg', 'height': 500, 'width': 1000}, 'text': {'plainText': 'Getty Images\n\nChelsea Handler is calling out two fellow comedians, and one just responded.\n\nWhile appearing on a recent episode of the Funny Knowing You podcast with Deon Cole, she called out Shane Gillis and Tony Hinchcliffe, who both appeared on the Roast of Kevin Hart alongside her.\n\nSpecifically, she said she received messages calling them “racist,” “bigots” and “sexist” after the roast: “They’re racist, that they’re bigots, they’re sexist.”\n\nShe was also asked about their choice of roast jokes. She responded, “No. I mean, it was ick. It was gross.”\n\nThere was a comment made during the roast by Hinchcliffe, who, if you don’t recall,'}, 'source': {'homepage': {'url': 'https://www.justjared.com/', 'label': 'Just Jared'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65850830', 'byline': 'Todd Spangler', 'date': '2026-05-21T11:18:20Z', 'externalUrl': 'https://variety.com/2026/digital/news/netflix-livestream-charlamagne-tha-god-breakfast-club-show-1236755352/', 'articleTitle': {'plainText': 'Netflix Will Soon Start Livestreaming Charlamagne Tha God’s ‘Breakfast Club’ Worldwide in Deal With iHeartMedia, Marking Its First Live Daily Show'}, 'image': {'__typename': 'Image', 'id': 'rm3896299010', 'url': 'https://m.media-amazon.com/images/M/MV5BNGVkNzk5NzMtNTJjNi00MDk1LWJhYWEtYmE2MGUxZGVmYTU1XkEyXkFqcGc@._V1_.jpg', 'height': 618, 'width': 927}, 'text': {'plainText': 'Live from New York: It’s Charlamagne Tha God and the crew from “The Breakfast Club” morning talk show — on Netflix.\n\nStarting June 1, Netflix will stream “The Breakfast Club” live daily, available to subscribers worldwide. It will become the streamer’s first daily live program, airing each weekday starting (bright and early!) at 6 a.m. Eastern.\n\nThe Netflix livestream will feature nearly three hours of uninterrupted programming, featuring commentary from Charlamagne and co-hosts DJ Envy, Jess Hilarious and Loren LoRosa and interviews with guests. While “The Breakfast Club’s” radio broadcast will continue to include traditional commercial breaks, on Netflix viewers will have an “uninterrupted experience” — with ad breaks filled by exclusive bonus segments including behind-the-scenes moments and extended discussions.\n\nThe video-podcast version of “The Breakfast Club” moved to Netflix in January 2026, when full episodes of the show stopped being distributed on YouTube — prompting some fans to express frustration that'}, 'source': {'homepage': {'url': 'http://variety.com/', 'label': 'Variety Film + TV'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65850355', 'byline': 'McKinley Franklin', 'date': '2026-05-21T00:31:53Z', 'externalUrl': 'https://www.hollywoodreporter.com/tv/tv-news/chelsea-handler-shane-gillis-tony-hinchcliffe-racist-kevin-hart-1236602897/', 'articleTitle': {'plainText': 'Chelsea Handler Slams Shane Gillis and Tony Hinchcliffe’s “Racist” Jokes at Kevin Hart Roast: “There Was So Much Disgustingness”'}, 'image': {'__typename': 'Image', 'id': 'rm590335490', 'url': 'https://m.media-amazon.com/images/M/MV5BNGM4MDc3YTUtNTMzZC00ODgxLWJhMzEtZGFlY2Q3ZDc4MjVhXkEyXkFqcGc@._V1_.jpg', 'height': 200, 'width': 200}, 'text': {'plainText': 'Chelsea Handler is sharing her distaste for Shane Gillis and Tony Hinchcliffe’s jokes at Netflix’s Roast of Kevin Hart, slamming them as “racist,” “bigots” and “sexist.”\n\nDuring a Wednesday appearance on the Funny Knowing You podcast with Deon Cole, the comedian said that she’d received messages on social media about Gillis and Hinchcliffe from their alleged former partners. When asked what they told her, Handler said, “It’s just everything we know, that they’re racist, that they’re bigots, they’re sexist.”\n\nCole asked if Handler liked any of their jokes during the roast in honor of Kevin Hart, to which she responded, “No. I mean, it was ick. It was gross.” She specifically called out a few jokes that Gillis and Hinchcliffe made during the Netflix special, with the first being Gillis’ joke about lynching. (“Kevin is so short, you’d have to lynch him from a bonsai tree,'}, 'source': {'homepage': {'url': 'http://www.hollywoodreporter.com/topic/movies', 'label': 'The Hollywood Reporter - Movie News'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65849244', 'byline': 'Hashim Asraff', 'date': '2026-05-20T12:10:47Z', 'externalUrl': 'https://fandomwire.com/who-is-kevin-hart-wife-everything-about-eniko-hart-and-her-marriage/', 'articleTitle': {'plainText': 'Who Is Kevin Hart’s Wife? Everything We Know About Eniko Hart and Her Marriage'}, 'image': {'__typename': 'Image', 'id': 'rm978898434', 'url': 'https://m.media-amazon.com/images/M/MV5BYmQxYjAxOTAtZjNlZC00MThjLWI0YzQtYzU4ZWEzMTg5ZmU4XkEyXkFqcGc@._V1_.jpg', 'height': 900, 'width': 1600}, 'text': {'plainText': 'Kevin Hart and his wife Eniko Hart are celebrating their 10th wedding anniversary this August. Hart recently shared a loving message to his wife during a chat with E! News at The Roast of Kevin Hart live event. He shared, “I appreciate you, I value you, I love you. Also, I need you. You’re the best.” Touching upon their anniversary, Hart shared, “We’re excited that we’re still here, that we’re still together, that we’re still growing an amazing household and family.”\n\nKevin and Eniko Hart’s marriage wasn’t easy, especially after his public 2017 cheating scandal. However, Eniko eventually forgave Hart and supported him through both tough times,'}, 'source': {'homepage': {'url': 'https://fandomwire.com/', 'label': 'FandomWire'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65849036', 'byline': 'Naser Nahandian', 'date': '2026-05-20T08:40:55Z', 'externalUrl': 'https://gazettely.com/2026/05/entertainment/roast-of-kevin-hart-netflix-ratings-viewers-tom-brady-comparison-2026/', 'articleTitle': {'plainText': 'Kevin Hart’s Netflix Roast Draws 13.5 Million Viewers — Just Behind Tom Brady’s Record'}, 'image': {'__typename': 'Image', 'id': 'rm188863744', 'url': 'https://m.media-amazon.com/images/M/MV5BMTY4OTAxMjkxN15BMl5BanBnXkFtZTgwODg5MzYyMTE@._V1_.jpg', 'height': 2048, 'width': 1362}, 'text': {'plainText': 'Netflix’s Roast of Kevin Hart pulled 13.5 million global views in its first week on the platform, claiming the No. 1 spot on the streamer’s English-language TV chart — though it landed just shy of the benchmark set two years ago by The Roast of Tom Brady, which drew 13.8 million views over the same period.\n\nThe gap between the two specials amounts to a 2% decrease in viewership. The comparison carries a certain irony: Hart himself hosted and exec produced the Brady roast before taking his own turn in the hot seat this year.\n\nThe Brady roast debuted with 2 million views on its premiere night before building to 13.8 million in its first full week.'}, 'source': {'homepage': {'url': 'https://gazettely.com/', 'label': 'Gazettely'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65848574', 'byline': 'Ari Coine', 'date': '2026-05-19T22:07:49Z', 'externalUrl': 'https://www.hollywoodoutbreak.com/2026/05/19/kevin-hart-animated-hit-swapped-lead-netflixs-newest-top-10/', 'articleTitle': {'plainText': 'Kevin Hart & Animated Hit ‘Swapped’ Lead Netflix’s Newest Top 10'}, 'image': {'__typename': 'Image', 'id': 'rm1228986114', 'url': 'https://m.media-amazon.com/images/M/MV5BNWFlNWM2Y2YtY2VhOC00MWFiLWExNWYtYWViYzJhMDQyMTJiXkEyXkFqcGc@._V1_.jpg', 'height': 12000, 'width': 8100}, 'text': {'plainText': 'Swapped – A buddy comedy about a small woodland creature (voiced by Michael B. Jordan) and a majestic bird (voiced by Juno Temple)—natural sworn enemies of The Valley—who suddenly swap bodies and must team up (while walking in each other’s feathers and fur) to survive the wildest adventure of their lives. Cr: Skydance Animation/Netflix © 2025\n\nKevin Hart is leading Netflix’s newest Top 10 in a major way this week. The comedian’s brutal live roast special exploded to No. 1 as audiences also pushed the animated hit Swapped into another huge streaming week. From gritty thrillers to emotional dramas and international breakout hits, Netflix’s latest rankings show just'}, 'source': {'homepage': {'url': 'http://www.hollywoodoutbreak.com', 'label': 'HollywoodOutbreak.com'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65848506', 'byline': 'Matt Grobar', 'date': '2026-05-19T21:34:37Z', 'externalUrl': 'https://deadline.com/2026/05/kevin-hart-roast-ratings-dip-tom-brady-year-1236916199/', 'articleTitle': {'plainText': 'Kevin Hart Netflix Roast Edged Out In Ratings By 2024 Roast Of Tom Brady'}, 'image': {'__typename': 'Image', 'id': 'rm3094597122', 'url': 'https://m.media-amazon.com/images/M/MV5BNjI5NzY5ZTItYjI5Ni00YzVjLWI1YTYtZTUxM2ZhYmFhMzAyXkEyXkFqcGc@._V1_.jpg', 'height': 901, 'width': 1600}, 'text': {'plainText': 'Kevin Hart’s roast at Netflix Is a Joke Fest 2026 came in just under the streamer’s 2024 roast of Tom Brady in Week 1 viewership.\n\nWhereas The Roast of Tom Brady notched 13.8M global views during its first week on Netflix, hitting #1 on the English-Language Top 10, Hart’s roast brought in 13.5M views over the same time frame, during the week of May 4-10. In any case, the roast again secured the No. 1 spot on the English TV list for the week.\n\nWe were first to report on Hart as the subject of this year’s roast at Netflix Is a Joke fest, whose dais included Sheryl Underwood, Chelsea Handler, Jeff Ross, Pete Davidson, Draymond Green, Tony Hinchcliffe, Regina Hall, and more.\n\nStreamed live from the Kia Forum in Inglewood, California, the event was hosted by Shane Gillis and also featured surprise appearances by Dwayne Johnson, Teyana Taylor, Tom Brady,'}, 'source': {'homepage': {'url': 'http://www.deadline.com/', 'label': 'Deadline Film + TV'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65848394', 'byline': 'Kasey Moore', 'date': '2026-05-19T19:50:14Z', 'externalUrl': 'https://www.whats-on-netflix.com/news/top-10-reports/kevin-hart-roast-berlin-season-2-nemesis/', 'articleTitle': {'plainText': 'Netflix Top 10s: Kevin Hart Roast Dominates (But Doesn’t Topple Tom Brady) Plus Debuts of Nemesis and Berlin S2'}, 'image': {'__typename': 'Image', 'id': 'rm1517407746', 'url': 'https://m.media-amazon.com/images/M/MV5BM2U3NzYxNzMtOWFhYS00NzcxLWJlNzgtZTgxOTA4NjUyOTBkXkEyXkFqcGc@._V1_.jpg', 'height': 720, 'width': 1280}, 'text': {'plainText': 'Picture Credits: Netflix\n\nWelcome to your weekly breakdown of the global Netflix Top 10s for the week of May 11 to May 17. This week, the animated hit Swapped continues its spectacular reign on the film side, while comedy and true-crime dominate the English TV charts with The Roast of Kevin Hart and Worst Ex Ever leading the pack. We’re also tracking the debuts of major new series like Courtney Kemp’s Nemesis, the latest Money Heist spin-off installment, and a surprisingly strong documentary launch.\n\nBefore we dive into the full analysis, a quick note on what didn’t quite make the cut: amongst the titles missing the global charts this'}, 'source': {'homepage': {'url': 'https://www.whats-on-netflix.com/', 'label': 'Whats-on-Netflix'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65848298', 'byline': 'Ashley Lee', 'date': '2026-05-19T18:13:40Z', 'externalUrl': 'https://www.netflix.com/tudum/articles/top-10-may-11-2026', 'articleTitle': {'plainText': 'Top 10 Movies and Shows on Netflix: Week of May 11, 2026'}, 'image': {'__typename': 'Image', 'id': 'rm3799961090', 'url': 'https://m.media-amazon.com/images/M/MV5BMGI3NzY1MDItNjVjZi00NDVjLThiZDItNGQwZmU3ZDFkZmNmXkEyXkFqcGc@._V1_.jpg', 'height': 675, 'width': 1200}, 'text': {'plainText': '“Let it burn,” sang Usher at The Roast of Kevin Hart, which lit up the No. 1 spot on the English TV list with 13.5 million views. The special put the actor and comedian in the hot seat for all the smoke from Sheryl Underwood, Chelsea Handler, Jeff Ross, Pete Davidson, Draymond Green, Tony Hinchcliffe, Regina Hall, and more. Plus, Dwayne Johnson, Teyana Taylor, Tom Brady, Lizzo, Venus and Serena Williams, and Katt Williams made surprise appearances, adding fuel to the fire. Shane Gillis hosted the raw and ruthless night of laughs, which streamed live from the Kia Forum in Inglewood, California, as part of Netflix is a Joke Fest.\n\nSwapped is'}, 'source': {'homepage': {'url': 'https://www.netflix.com/tudum', 'label': 'Tudum - Netflix'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65847209', 'byline': 'Alexis Rios', 'date': '2026-05-19T03:40:06Z', 'externalUrl': 'https://uinterview.com/news/tom-brady-makes-runway-debut-for-gucci-fashion-show-in-times-square/', 'articleTitle': {'plainText': 'Tom Brady Makes Runway Debut For Gucci Fashion Show In Times Square'}, 'image': {'__typename': 'Image', 'id': 'rm3012939266', 'url': 'https://m.media-amazon.com/images/M/MV5BMmViZWVlMGYtY2NhMy00ZTNlLTllNTctNjgwMTUxNTU5YjZjXkEyXkFqcGc@._V1_.jpg', 'height': 870, 'width': 1200}, 'text': {'plainText': 'Seven-time Super Bowl champion Tom Brady was decked out in full Gucci leather on Saturday evening.\n\nThe Gucci Resort 2027 collection fashion show was held in the middle of Times Square, where Brady made his catwalk debut. Brady was sporting a full black leather ensemble, jacket, pants and black leather boots while striding down the runway.\n\nThe retired New England Patriots star wasn’t the only celebrity to make an appearance at the show. Paris Hilton and Emily Ratajkowski also walked the runway with Cindy Crawford, closing the show. Celebrity guests such as Kim Kardashian, Mariah Carey, Anna Wintour, Shawn Mendes and Lindsay Lohan were in attendance.\n\nWhile this is Brady'}, 'source': {'homepage': {'url': 'http://www.uinterview.com', 'label': 'Uinterview'}, 'description': None}}}, {'node': {'__typename': 'News', 'id': 'ni65846405', 'byline': 'Matt Grobar', 'date': '2026-05-18T17:00:00Z', 'externalUrl': 'https://deadline.com/2026/05/usama-siddiquee-signs-wme-1236914635/', 'articleTitle': {'plainText': 'WME Signs ‘Funny Af’ Standout Usama Siddiquee'}, 'image': {'__typename': 'Image', 'id': 'rm1501613570', 'url': 'https://m.media-amazon.com/images/M/MV5BYjIyYTU1MDYtZGNmNS00MTM1LWJjZGEtZGU0ODczZTA4NzE5XkEyXkFqcGc@._V1_.jpg', 'height': 3951, 'width': 5272}, 'text': {'plainText': 'Exclusive: Usama Siddiquee, the Bengali-American comedian recently named runner-up of Kevin Hart’s Funny Af, has inked with WME for representation in all areas, with an eye toward expanding opportunities in touring, television, film, and digital.\n\nNamed to our December list of the Stand-Ups to Keep an Eye On in 2026, Siddiquee emerged as one of the most-discussed names of Netflix Is a Joke Fest 2026, with his work in the first season of Hart’s Netflix comedy competition series.\n\nKnown for his high-energy, rapid-fire style, th

In [4]:
df = pd.DataFrame(response.json())

In [5]:
df.head()

                                                   data
name  {'id': 'nm0366389', 'nameText': {'text': 'Kevi...

In [25]:
len(df.data)

1

## Creating dataset of movies

- API link1 :- https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=471
- API link2 :- https://api.themoviedb.org/3/genre/movie/list?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US

In [1]:
# id title release_date overview vote_averate vote_count

In [6]:
import requests
API_KEY = "267a7544b1e708c67296bc7117272a0e"
url = f"https://api.themoviedb.org/3/movie/top_rated?api_key={API_KEY}&language=en-US&page=1"

In [7]:
response = requests.get(url)

In [8]:
response.json().keys()

dict_keys(['page', 'results', 'total_pages', 'total_results'])

In [9]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
   'genre_ids': [12, 16, 10751, 14],
   'id': 1007757,
   'title': 'Swapped',
   'original_language': 'en',
   'original_title': 'Swapped',
   'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
   'popularity': 324.1286,
   'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
   'release_date': '2026-05-01',
   'softcore': False,
   'video': False,
   'vote_average': 8.978,
   'vote_count': 1247},
  {'adult': False,
   'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
   'genre_ids': [18, 80],
   'id': 278,
   'title': 'The Shawshank Redemption',
   'original_language': 'en',
   'original_title': 'The Shawshank Redemption',
   'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
   'popularity': 58.7166,
   'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
   'release_date': '1994-09-23',
   'softcore': False,
   'video': False,
   'vote_average': 8.721,
   'vote_count': 30374},
  {'adult': False,
   'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
   'genre_ids': [18, 80],
   'id': 238,
   'title': 'The Godfather',
   'original_language': 'en',
   'original_title': 'The Godfather',
   'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
   'popularity': 47.1045,
   'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
   'release_date': '1972-03-14',
   'softcore': False,
   'video': False,
   'vote_average': 8.686,
   'vote_count': 22919},
  {'adult': False,
   'backdrop_path': '/2I1OFQJ0L9T0dpU6FobKFWV2PxX.jpg',
   'genre_ids': [878, 12],
   'id': 687163,
   'title': 'Project Hail Mary',
   'original_language': 'en',
   'original_title': 'Project Hail Mary',
   'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
   'popularity': 402.3877,
   'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
   'release_date': '2026-03-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.6,
   'vote_count': 3790},
  {'adult': False,
   'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
   'genre_ids': [18, 80],
   'id': 240,
   'title': 'The Godfather Part II',
   'original_language': 'en',
   'original_title': 'The Godfather Part II',
   'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
   'popularity': 29.8549,
   'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
   'release_date': '1974-12-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.6,
   'vote_count': 13898},
  {'adult': False,
   'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
   'genre_ids': [18, 36, 10752],
   'id': 424,
   'title': "Schindler's List",
   'original_language': 'en',
   'original_title': "Schindler's List",
   'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
   'popularity': 39.6162,
   'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
   'release_date': '1993-12-15',
   'softcore': False,
   'video': False,
   'vote_average': 8.6,
   'vote_count': 17436},
  {'adult': False,
   'backdrop_path': '/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg',
   'genre_ids': [18],
   'id': 389,
   'title': '12 Angry Men',
   'original_language': 'en',
   'original_title': '12 Angry Men',
   'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
   'popularity': 22.7462,
   'poster_path': '/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg',
   'release_date': '1957-04-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.561,
   'vote_count': 9972},
  {'adult': False,
   'backdrop_path': '/bVGHSe47W6oCQL1Q88pvRAet51A.jpg',
   'genre_ids': [18, 9648],
   'id': 1330021,
   'title': 'Remarkably Bright Creatures',
   'original_language': 'en',
   'original_title': 'Remarkably Bright Creatures',
   'overview': 'Through unlikely bonds formed during night shifts at a local aquarium, Tova, an elderly widow, learns of a life-changing discovery that may bring her joy and wonder once again.',
   'popularity': 106.2885,
   'poster_path': '/9HcEqn3D4J6b2Z0jK54id9nA0fr.jpg',
   'release_date': '2026-05-07',
   'softcore': False,
   'video': False,
   'vote_average': 8.567,
   'vote_count': 352},
  {'adult': False,
   'backdrop_path': '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg',
   'genre_ids': [16, 10751, 14],
   'id': 129,
   'title': 'Spirited Away',
   'original_language': 'ja',
   'original_title': '千と千尋の神隠し',
   'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
   'popularity': 32.3547,
   'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
   'release_date': '2001-07-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.534,
   'vote_count': 18297},
  {'adult': False,
   'backdrop_path': '/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg',
   'genre_ids': [28, 80, 53],
   'id': 155,
   'title': 'The Dark Knight',
   'original_language': 'en',
   'original_title': 'The Dark Knight',
   'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
   'popularity': 38.3867,
   'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
   'release_date': '2008-07-16',
   'softcore': False,
   'video': False,
   'vote_average': 8.53,
   'vote_count': 35741},
  {'adult': False,
   'backdrop_path': '/6N5d02quKqMKqvTpOdFmBDy9scY.jpg',
   'genre_ids': [35, 18, 10749],
   'id': 19404,
   'title': 'Dilwale Dulhania Le Jayenge',
   'original_language': 'hi',
   'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
   'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
   'popularity': 16.2214,
   'poster_path': '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
   'release_date': '1995-10-20',
   'softcore': False,
   'video': False,
   'vote_average': 8.512,
   'vote_count': 4589},
  {'adult': False,
   'backdrop_path': '/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg',
   'genre_ids': [14, 18, 80],
   'id': 497,
   'title': 'The Green Mile',
   'original_language': 'en',
   'original_title': 'The Green Mile',
   'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
   'popularity': 29.0682,
   'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
   'release_date': '1999-12-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.506,
   'vote_count': 19233},
  {'adult': False,
   'backdrop_path': '/qO55CD8tgVL1T4WKn6zYFFiD6lL.jpg',
   'genre_ids': [28, 18, 80],
   'id': 1439930,
   'title': 'The Punisher: One Last Kill',
   'original_language': 'en',
   'original_title': 'The Punisher: One Last Kill',
   'overview': 'As Frank Castle searches for meaning beyond revenge, an unexpected force pulls him back into the fight.',
   'popularity': 593.9964,
   'poster_path': '/qQclTgLMDvGBuUBFGHRipxkEwWR.jpg',
   'release_date': '2026-05-12',
   'softcore': False,
   'video': False,
   'vote_average': 8.5,
   'vote_count': 1032},
  {'adult': False,
   'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
   'genre_ids': [12, 14, 28],
   'id': 122,
   'title': 'The Lord of the Rings: The Return of the King',
   'original_language': 'en',
   'original_title': 'The Lord of the Rings: The Return of the King',
   'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
   'popularity': 39.3061,
   'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
   'release_date': '2003-12-17',
   'softcore': False,
   'video': False,
   'vote_average': 8.5,
   'vote_count': 26505},
  {'adult': False,
   'backdrop_path': '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
   'genre_ids': [35, 53, 18],
   'id': 496243,
   'title': 'Parasite',
   'original_language': 'ko',
   'original_title': '기생충',
   'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
   'popularity': 36.4249,
   'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
   'release_date': '2019-05-30',
   'softcore': False,
   'video': False,
   'vote_average': 8.494,
   'vote_count': 20607},
  {'adult': False,
   'backdrop_path': '/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg',
   'genre_ids': [35, 10749],
   'id': 1181678,
   'title': '¿Quieres ser mi hijo?',
   'original_language': 'en',
   'original_title': '¿Quieres ser mi hijo?',
   'overview': 'Lu, a conformist woman in her forties, learns that her 15-year partner has been having extramarital affairs. Starting from scratch, she gets involved in an unexpected relationship with a young womanizer.',
   'popularity': 13.8919,
   'poster_path': '/9GuvODahvuFqdhuZ16aBLR4UJoP.jpg',
   'release_date': '2023-09-21',
   'softcore': False,
   'video': False,
   'vote_average': 8.482,
   'vote_count': 339},
  {'adult': False,
   'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
   'genre_ids': [53, 80, 35],
   'id': 680,
   'title': 'Pulp Fiction',
   'original_language': 'en',
   'original_title': 'Pulp Fiction',
   'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
   'popularity': 38.1996,
   'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
   'release_date': '1994-09-10',
   'softcore': False,
   'video': False,
   'vote_average': 8.484,
   'vote_count': 30165},
  {'adult': False,
   'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
   'genre_ids': [16, 10749, 18],
   'id': 372058,
   'title': 'Your Name.',
   'original_language': 'ja',
   'original_title': '君の名は。',
   'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
   'popularity': 29.5353,
   'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
   'release_date': '2016-08-26',
   'softcore': False,
   'video': False,
   'vote_average': 8.5,
   'vote_count': 12541},
  {'adult': False,
   'backdrop_path': '/2ssWTSVklAEc98frZUQhgtGHx7s.jpg',
   'genre_ids': [12, 18, 878],
   'id': 157336,
   'title': 'Interstellar',
   'original_language': 'en',
   'original_title': 'Interstellar',
   'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
   'popularity': 68.2647,
   'poster_path': '/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
   'release_date': '2014-11-05',
   'softcore': False,
   'video': False,
   'vote_average': 8.474,
   'vote_count': 39760},
  {'adult': False,
   'backdrop_path': '/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg',
   'genre_ids': [37],
   'id': 429,
   'title': 'The Good, the Bad and the Ugly',
   'original_language': 'it',
   'original_title': 'Il buono, il brutto, il cattivo',
   'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
   'popularity': 20.9276,
   'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
   'release_date': '1966-12-23',
   'softcore': False,
   'video': False,
   'vote_average': 8.469,
   'vote_count': 9619}],
 'total_pages': 544,
 'total_results': 10864}

In [10]:
response.json()['results']

[{'adult': False,
  'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
  'genre_ids': [12, 16, 10751, 14],
  'id': 1007757,
  'title': 'Swapped',
  'original_language': 'en',
  'original_title': 'Swapped',
  'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
  'popularity': 324.1286,
  'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
  'release_date': '2026-05-01',
  'softcore': False,
  'video': False,
  'vote_average': 8.978,
  'vote_count': 1247},
 {'adult': False,
  'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
  'genre_ids': [18, 80],
  'id': 278,
  'title': 'The Shawshank Redemption',
  'original_language': 'en',
  'original_title': 'The Shawshank Redemption',
  'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
  'popularity': 58.7166,
  'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
  'release_date': '1994-09-23',
  'softcore': False,
  'video': False,
  'vote_average': 8.721,
  'vote_count': 30374},
 {'adult': False,
  'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
  'genre_ids': [18, 80],
  'id': 238,
  'title': 'The Godfather',
  'original_language': 'en',
  'original_title': 'The Godfather',
  'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
  'popularity': 47.1045,
  'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  'release_date': '1972-03-14',
  'softcore': False,
  'video': False,
  'vote_average': 8.686,
  'vote_count': 22919},
 {'adult': False,
  'backdrop_path': '/2I1OFQJ0L9T0dpU6FobKFWV2PxX.jpg',
  'genre_ids': [878, 12],
  'id': 687163,
  'title': 'Project Hail Mary',
  'original_language': 'en',
  'original_title': 'Project Hail Mary',
  'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
  'popularity': 402.3877,
  'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
  'release_date': '2026-03-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.6,
  'vote_count': 3790},
 {'adult': False,
  'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
  'genre_ids': [18, 80],
  'id': 240,
  'title': 'The Godfather Part II',
  'original_language': 'en',
  'original_title': 'The Godfather Part II',
  'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
  'popularity': 29.8549,
  'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
  'release_date': '1974-12-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.6,
  'vote_count': 13898},
 {'adult': False,
  'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
  'genre_ids': [18, 36, 10752],
  'id': 424,
  'title': "Schindler's List",
  'original_language': 'en',
  'original_title': "Schindler's List",
  'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
  'popularity': 39.6162,
  'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
  'release_date': '1993-12-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.6,
  'vote_count': 17436},
 {'adult': False,
  'backdrop_path': '/w4bTBXcqXc2TUyS5Fc4h67uWbPn.jpg',
  'genre_ids': [18],
  'id': 389,
  'title': '12 Angry Men',
  'original_language': 'en',
  'original_title': '12 Angry Men',
  'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
  'popularity': 22.7462,
  'poster_path': '/zhG3vKWyDRaZYoaww1UVAi29T9h.jpg',
  'release_date': '1957-04-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.561,
  'vote_count': 9972},
 {'adult': False,
  'backdrop_path': '/bVGHSe47W6oCQL1Q88pvRAet51A.jpg',
  'genre_ids': [18, 9648],
  'id': 1330021,
  'title': 'Remarkably Bright Creatures',
  'original_language': 'en',
  'original_title': 'Remarkably Bright Creatures',
  'overview': 'Through unlikely bonds formed during night shifts at a local aquarium, Tova, an elderly widow, learns of a life-changing discovery that may bring her joy and wonder once again.',
  'popularity': 106.2885,
  'poster_path': '/9HcEqn3D4J6b2Z0jK54id9nA0fr.jpg',
  'release_date': '2026-05-07',
  'softcore': False,
  'video': False,
  'vote_average': 8.567,
  'vote_count': 352},
 {'adult': False,
  'backdrop_path': '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg',
  'genre_ids': [16, 10751, 14],
  'id': 129,
  'title': 'Spirited Away',
  'original_language': 'ja',
  'original_title': '千と千尋の神隠し',
  'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
  'popularity': 32.3547,
  'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
  'release_date': '2001-07-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.534,
  'vote_count': 18297},
 {'adult': False,
  'backdrop_path': '/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg',
  'genre_ids': [28, 80, 53],
  'id': 155,
  'title': 'The Dark Knight',
  'original_language': 'en',
  'original_title': 'The Dark Knight',
  'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
  'popularity': 38.3867,
  'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  'release_date': '2008-07-16',
  'softcore': False,
  'video': False,
  'vote_average': 8.53,
  'vote_count': 35741},
 {'adult': False,
  'backdrop_path': '/6N5d02quKqMKqvTpOdFmBDy9scY.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 19404,
  'title': 'Dilwale Dulhania Le Jayenge',
  'original_language': 'hi',
  'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
  'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
  'popularity': 16.2214,
  'poster_path': '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
  'release_date': '1995-10-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.512,
  'vote_count': 4589},
 {'adult': False,
  'backdrop_path': '/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg',
  'genre_ids': [14, 18, 80],
  'id': 497,
  'title': 'The Green Mile',
  'original_language': 'en',
  'original_title': 'The Green Mile',
  'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
  'popularity': 29.0682,
  'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
  'release_date': '1999-12-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.506,
  'vote_count': 19233},
 {'adult': False,
  'backdrop_path': '/qO55CD8tgVL1T4WKn6zYFFiD6lL.jpg',
  'genre_ids': [28, 18, 80],
  'id': 1439930,
  'title': 'The Punisher: One Last Kill',
  'original_language': 'en',
  'original_title': 'The Punisher: One Last Kill',
  'overview': 'As Frank Castle searches for meaning beyond revenge, an unexpected force pulls him back into the fight.',
  'popularity': 593.9964,
  'poster_path': '/qQclTgLMDvGBuUBFGHRipxkEwWR.jpg',
  'release_date': '2026-05-12',
  'softcore': False,
  'video': False,
  'vote_average': 8.5,
  'vote_count': 1032},
 {'adult': False,
  'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
  'genre_ids': [12, 14, 28],
  'id': 122,
  'title': 'The Lord of the Rings: The Return of the King',
  'original_language': 'en',
  'original_title': 'The Lord of the Rings: The Return of the King',
  'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
  'popularity': 39.3061,
  'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
  'release_date': '2003-12-17',
  'softcore': False,
  'video': False,
  'vote_average': 8.5,
  'vote_count': 26505},
 {'adult': False,
  'backdrop_path': '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
  'genre_ids': [35, 53, 18],
  'id': 496243,
  'title': 'Parasite',
  'original_language': 'ko',
  'original_title': '기생충',
  'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
  'popularity': 36.4249,
  'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  'release_date': '2019-05-30',
  'softcore': False,
  'video': False,
  'vote_average': 8.494,
  'vote_count': 20607},
 {'adult': False,
  'backdrop_path': '/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg',
  'genre_ids': [35, 10749],
  'id': 1181678,
  'title': '¿Quieres ser mi hijo?',
  'original_language': 'en',
  'original_title': '¿Quieres ser mi hijo?',
  'overview': 'Lu, a conformist woman in her forties, learns that her 15-year partner has been having extramarital affairs. Starting from scratch, she gets involved in an unexpected relationship with a young womanizer.',
  'popularity': 13.8919,
  'poster_path': '/9GuvODahvuFqdhuZ16aBLR4UJoP.jpg',
  'release_date': '2023-09-21',
  'softcore': False,
  'video': False,
  'vote_average': 8.482,
  'vote_count': 339},
 {'adult': False,
  'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
  'genre_ids': [53, 80, 35],
  'id': 680,
  'title': 'Pulp Fiction',
  'original_language': 'en',
  'original_title': 'Pulp Fiction',
  'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
  'popularity': 38.1996,
  'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
  'release_date': '1994-09-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.484,
  'vote_count': 30165},
 {'adult': False,
  'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg',
  'genre_ids': [16, 10749, 18],
  'id': 372058,
  'title': 'Your Name.',
  'original_language': 'ja',
  'original_title': '君の名は。',
  'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
  'popularity': 29.5353,
  'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
  'release_date': '2016-08-26',
  'softcore': False,
  'video': False,
  'vote_average': 8.5,
  'vote_count': 12541},
 {'adult': False,
  'backdrop_path': '/2ssWTSVklAEc98frZUQhgtGHx7s.jpg',
  'genre_ids': [12, 18, 878],
  'id': 157336,
  'title': 'Interstellar',
  'original_language': 'en',
  'original_title': 'Interstellar',
  'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
  'popularity': 68.2647,
  'poster_path': '/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
  'release_date': '2014-11-05',
  'softcore': False,
  'video': False,
  'vote_average': 8.474,
  'vote_count': 39760},
 {'adult': False,
  'backdrop_path': '/Adrip2Jqzw56KeuV2nAxucKMNXA.jpg',
  'genre_ids': [37],
  'id': 429,
  'title': 'The Good, the Bad and the Ugly',
  'original_language': 'it',
  'original_title': 'Il buono, il brutto, il cattivo',
  'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.',
  'popularity': 20.9276,
  'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg',
  'release_date': '1966-12-23',
  'softcore': False,
  'video': False,
  'vote_average': 8.469,
  'vote_count': 9619}]

In [29]:
# here it is providing genre_ids instead of genre names, we need to convert them to genre names using the genre ids and genre names mapping provided by the api.

In [30]:
genre_url = f"https://api.themoviedb.org/3/genre/movie/list?api_key={API_KEY}&language=en-US"
genre_response = requests.get(genre_url)
genre_response.json()

{'genres': [{'id': 28, 'name': 'Action'},
  {'id': 12, 'name': 'Adventure'},
  {'id': 16, 'name': 'Animation'},
  {'id': 35, 'name': 'Comedy'},
  {'id': 80, 'name': 'Crime'},
  {'id': 99, 'name': 'Documentary'},
  {'id': 18, 'name': 'Drama'},
  {'id': 10751, 'name': 'Family'},
  {'id': 14, 'name': 'Fantasy'},
  {'id': 36, 'name': 'History'},
  {'id': 27, 'name': 'Horror'},
  {'id': 10402, 'name': 'Music'},
  {'id': 9648, 'name': 'Mystery'},
  {'id': 10749, 'name': 'Romance'},
  {'id': 878, 'name': 'Science Fiction'},
  {'id': 10770, 'name': 'TV Movie'},
  {'id': 53, 'name': 'Thriller'},
  {'id': 10752, 'name': 'War'},
  {'id': 37, 'name': 'Western'}]}

In [31]:
genre_dict = {}
for genre in genre_response.json()['genres']:
    genre_dict[genre["id"]] = genre["name"]

In [32]:
df = pd.DataFrame(response.json()['results'])[['title', 'overview', 'genre_ids']]

In [33]:
df.head()

,title,overview,genre_ids
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"[18, 80]"
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[18, 80]"
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[18, 80]"
3,Schindler's List,The true story of how businessman Oskar Schind...,"[18, 36, 10752]"
4,12 Angry Men,The defense and the prosecution have rested an...,[18]

In [ ]:
# now we are fetching data of all the 428 pages
df = pd.DataFrame()
for i in range(1, 429):
    url = f"https://api.themoviedb.org/3/movie/top_rated?api_key={API_KEY}&language=en-US&page={i}"
    response = requests.get(url)
    temp_df = pd.DataFrame(response.json()['results'])[['title', 'overview', 'genre_ids']]
    df = pd.concat([df, temp_df], ignore_index = True)

In [36]:
genre_dict

{28: 'Action',
 12: 'Adventure',
 16: 'Animation',
 35: 'Comedy',
 80: 'Crime',
 99: 'Documentary',
 18: 'Drama',
 10751: 'Family',
 14: 'Fantasy',
 36: 'History',
 27: 'Horror',
 10402: 'Music',
 9648: 'Mystery',
 10749: 'Romance',
 878: 'Science Fiction',
 10770: 'TV Movie',
 53: 'Thriller',
 10752: 'War',
 37: 'Western'}

In [37]:
genres = []
for ids in df.genre_ids:
    genre_names = [genre_dict[id] for id in ids]
    genres.append(genre_names)

df["genre"] = genres

df.rename(
    columns = {
        "overview": "description",
        "title": "movie_name"
    }, inplace = True
)

In [38]:
df.head()

,movie_name,description,genre_ids,genre
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"[18, 80]","[Drama, Crime]"
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[18, 80]","[Drama, Crime]"
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[18, 80]","[Drama, Crime]"
3,Schindler's List,The true story of how businessman Oskar Schind...,"[18, 36, 10752]","[Drama, History, War]"
4,12 Angry Men,The defense and the prosecution have rested an...,[18],[Drama]

In [39]:
df.drop("genre_ids", axis = 1, inplace = True)

In [40]:
df.head()

,movie_name,description,genre
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"[Drama, Crime]"
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","[Drama, Crime]"
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"[Drama, Crime]"
3,Schindler's List,The true story of how businessman Oskar Schind...,"[Drama, History, War]"
4,12 Angry Men,The defense and the prosecution have rested an...,[Drama]

In [41]:
df.dtypes

movie_name     object
description    object
genre          object
dtype: object

In [42]:
df['genre'] = df['genre'].apply(lambda X: ", ".join(X))

In [43]:
df.head()

,movie_name,description,genre
0,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,"Drama, Crime"
1,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...","Drama, Crime"
2,The Godfather Part II,In the continuing saga of the Corleone crime f...,"Drama, Crime"
3,Schindler's List,The true story of how businessman Oskar Schind...,"Drama, History, War"
4,12 Angry Men,The defense and the prosecution have rested an...,Drama

In [45]:
df.to_csv("movies.csv")

In [46]:
df.columns

Index(['movie_name', 'description', 'genre'], dtype='object')